const products = [
  {
    productID: 1,
    name: "Laptop",
    price: 899.99,
    stock: 50,
    category: "Electronics",
    rating: 4.5,
  },
  {
    productID: 2,
    name: "Smartphone",
    price: 599.99,
    stock: 150,
    category: "Electronics",
    rating: 4.3,
  },
  {
    productID: 3,
    name: "Wireless Headphones",
    price: 129.99,
    stock: 200,
    category: "Electronics",
    rating: 4.7,
  },
  {
    productID: 4,
    name: "Bluetooth Speaker",
    price: 49.99,
    stock: 100,
    category: "Electronics",
    rating: 4.2,
  },
  {
    productID: 5,
    name: "Smartwatch",
    price: 199.99,
    stock: 75,
    category: "Electronics",
    rating: 4.6,
  },
  {
    productID: 6,
    name: "Gaming Chair",
    price: 189.99,
    stock: 30,
    category: "Furniture",
    rating: 4.8,
  },
  {
    productID: 7,
    name: "LED Monitor",
    price: 249.99,
    stock: 40,
    category: "Electronics",
    rating: 4.4,
  },
  {
    productID: 8,
    name: "Desk Lamp",
    price: 29.99,
    stock: 120,
    category: "Furniture",
    rating: 4.1,
  },
  {
    productID: 9,
    name: "Bluetooth Earbuds",
    price: 59.99,
    stock: 85,
    category: "Electronics",
    rating: 4.3,
  },
  {
    productID: 10,
    name: "4K TV",
    price: 499.99,
    stock: 50,
    category: "Electronics",
    rating: 4.5,
  },
  {
    productID: 11,
    name: "Jeans",
    price: 39.99,
    stock: 200,
    category: "Clothing",
    rating: 4.2,
  },
  {
    productID: 12,
    name: "T-shirt",
    price: 19.99,
    stock: 300,
    category: "Clothing",
    rating: 4.4,
  },
  {
    productID: 13,
    name: "Sneakers",
    price: 79.99,
    stock: 150,
    category: "Footwear",
    rating: 4.6,
  },
  {
    productID: 14,
    name: "Sweater",
    price: 49.99,
    stock: 100,
    category: "Clothing",
    rating: 4.5,
  },
  {
    productID: 15,
    name: "Jacket",
    price: 89.99,
    stock: 75,
    category: "Clothing",
    rating: 4.7,
  },
  {
    productID: 16,
    name: "Running Shoes",
    price: 99.99,
    stock: 120,
    category: "Footwear",
    rating: 4.3,
  },
  {
    productID: 17,
    name: "Backpack",
    price: 59.99,
    stock: 200,
    category: "Accessories",
    rating: 4.2,
  },
  {
    productID: 18,
    name: "Watch",
    price: 149.99,
    stock: 90,
    category: "Accessories",
    rating: 4.6,
  },
  {
    productID: 19,
    name: "Sunglasses",
    price: 29.99,
    stock: 180,
    category: "Accessories",
    rating: 4.1,
  },
  {
    productID: 20,
    name: "Phone Case",
    price: 19.99,
    stock: 250,
    category: "Accessories",
    rating: 4.0,
  },
];
